PROP_FIRM_CONFIGS = {

    "TOPSTEP_50K": {
        "firm": "Topstep",
        "account_size": 50_000,
        "monthly_cost_usd": 49,
        "profit_target": 3_000,
        "max_loss_limit": 2_000,
        "trailing_type": "EOD",
        "trailing_stops_at_profit": None,
        "max_contracts": 5,
        "daily_loss_limit": None,
        "profit_split": 0.90,
        "first_withdrawal_bonus": 10_000,
        "min_payout_days": 5,
        "min_winning_day_pnl": 200,
        "max_payout_per_request": 5_000,
        "payout_max_pct": 0.50,
        "instruments": ["MES", "MNQ", "ES", "NQ", "CL", "GC"],
        "exchange": "CME/CBOT/NYMEX/COMEX",
        "news_trading_allowed": True,
        "activation_fee": 0,
        "notes": "MLL trails EOD high-water mark. No daily loss limit since Aug 2024.",
        "config_version": "2024-08",
    },

    "TOPSTEP_100K": {
        "firm": "Topstep",
        "account_size": 100_000,
        "monthly_cost_usd": 99,
        "profit_target": 6_000,
        "max_loss_limit": 3_000,
        "trailing_type": "EOD",
        "trailing_stops_at_profit": None,
        "max_contracts": 10,
        "daily_loss_limit": None,
        "profit_split": 0.90,
        "first_withdrawal_bonus": 10_000,
        "min_payout_days": 5,
        "min_winning_day_pnl": 200,
        "max_payout_per_request": 5_000,
        "payout_max_pct": 0.50,
        "instruments": ["MES", "MNQ", "ES", "NQ", "CL", "GC"],
        "exchange": "CME/CBOT/NYMEX/COMEX",
        "news_trading_allowed": True,
        "activation_fee": 0,
        "config_version": "2024-08",
    },

    "TOPSTEP_150K": {
        "firm": "Topstep",
        "account_size": 150_000,
        "monthly_cost_usd": 149,
        "profit_target": 9_000,
        "max_loss_limit": 4_500,
        "trailing_type": "EOD",
        "trailing_stops_at_profit": None,
        "max_contracts": 15,
        "daily_loss_limit": None,
        "profit_split": 0.90,
        "first_withdrawal_bonus": 10_000,
        "min_payout_days": 5,
        "min_winning_day_pnl": 200,
        "max_payout_per_request": 5_000,
        "payout_max_pct": 0.50,
        "instruments": ["MES", "MNQ", "ES", "NQ", "CL", "GC"],
        "exchange": "CME/CBOT/NYMEX/COMEX",
        "news_trading_allowed": True,
        "activation_fee": 0,
        "config_version": "2024-08",
    },

    "APEX_50K": {
        "firm": "Apex Trader Funding",
        "account_size": 50_000,
        "monthly_cost_usd": 167,
        "profit_target": 3_000,
        "max_loss_limit": 2_500,
        "trailing_type": "INTRADAY",
        "trailing_stops_at_profit": 2_500,
        "max_contracts": 10,
        "pa_max_contracts": 6,
        "daily_loss_limit": None,
        "profit_split": 0.90,
        "min_payout_days": None,
        "consistency_rule": True,
        "instruments": ["MES", "MNQ", "ES", "NQ"],
        "exchange": "CME",
        "news_trading_allowed": False,
        "activation_fee": 85,
        "config_version": "2024-08",
    },

    "APEX_100K": {
        "firm": "Apex Trader Funding",
        "account_size": 100_000,
        "monthly_cost_usd": 207,
        "profit_target": 6_000,
        "max_loss_limit": 3_000,
        "trailing_type": "INTRADAY",
        "trailing_stops_at_profit": 3_000,
        "max_contracts": 14,
        "pa_max_contracts": 10,
        "daily_loss_limit": None,
        "profit_split": 0.90,
        "consistency_rule": True,
        "instruments": ["MES", "MNQ", "ES", "NQ"],
        "exchange": "CME",
        "news_trading_allowed": False,
        "activation_fee": 85,
        "config_version": "2024-08",
    },

    "FTMO_100K": {
        "firm": "FTMO",
        "account_size": 100_000,
        "monthly_cost_usd": 0,
        "challenge_fee_eur": 540,
        "profit_target": 10_000,       # 10% of account
        "profit_target_pct": 0.10,
        "verification_target_pct": 0.05,
        "max_loss_limit": 10_000,      # 10% of account
        "max_loss_pct": 0.10,
        "max_daily_loss_pct": 0.05,
        "trailing_type": "EOD",
        "trailing_stops_at_profit": None,
        "max_contracts": None,
        "daily_loss_limit": 5_000,
        "profit_split": 0.80,
        "instruments": ["ES", "NQ", "CL", "GC", "ZB"],
        "exchange": "CME",
        "news_trading_allowed": True,
        "min_trading_days": 4,
        "notes": "Two-step evaluation. Strict daily loss limit. No size limit.",
        "config_version": "2024-08",
    },
}
